### ISSUE TITLE
As a non-tech-savvy user, I want to be able to select which project I want to contribute to so that I can collaborate in something I am interested in.

### ISSUE THREAD

**Issue by salvacorts** [salvacorts/TFG-Parasitic-Metaheuristics#14]
**User Story**
As a user of the platform that wants to contribute, I want to be able to pick a project I care about. This will encourage me to invest more time collaborating in the platform as well as sharing it with other people.

**Acceptance criteria**
- Show a catalogue of available problems
- By choosing one the user will be redirected to the website where they will start collaborating
- Open the problem website in a new tab
- Show Problem Title
- Show problem description
- Optionally show related documentation (e.g. Papers, Websites, etc...)
- Link to source code that will be executed on the user's browser

**Definition of Done**
- [ ] Code Builds without error warning
- [ ] Code is Unit Tested
- [ ] Code is Deployed to system test environment and passed system tests
- [ ] Build pushed to a demo server 
- [ ] Documentation

**Comment by JJ** [comment]
Probably some meta-info about available problems, including open papers and links to data repository. This anyway is not high priority. In most cases, releasing a link via social networks is more than enough. If you add to this issue the fact that the user needs to be very well informed of what's going on in a open way, it could fit.

**Comment by JJ** [comment]
I would say this is the same *persona* as #13 . All non-tech-savvy users could be merged.

**Comment by salvacorts** [comment]
> Probably some meta-info about available problems, including open papers and links to data repository. This anyway is not high priority. In most cases, releasing a link via social networks is more than enough. If you add to this issue the fact that the user needs to be very well informed of what's going on in a open way, it could fit.

Thats a good point, I like it. I think it is important to provide more information about the problem he is contributing to appart from the title of the problem itself. I will modify this issue as well as creating a user story about it from the researcher point of view.

> I would say this is the same persona as #13 . All non-tech-savvy users could be merged.

Yes, it is the same persona but not the same user story. I think we should keep them spearated since implementing one is independent of the other and they can work separately.

For example, If I send you a link that executes the code to contribute to a problem is different from providing you an interface where you can pick the problem you want from a catalogue and then start contributing to it.

Both are related but can work separately.

**Comment by JJ** [comment]
El mar., 28 may. 2019 a las 10:43, Salva Corts (<notifications@github.com>)
escribió:

> Probably some meta-info about available problems, including open papers
> and links to data repository. This anyway is not high priority. In most
> cases, releasing a link via social networks is more than enough. If you add
> to this issue the fact that the user needs to be very well informed of
> what's going on in a open way, it could fit.
>
> Thats a good point, I like it. I think it is important to provide more
> information about the problem he is contributing to appart from the title
> of the problem itself. I will modify this issue as well as creating a user
> story about it from the researcher point of view.
>
> I would say this is the same persona as #13
> <https://github.com/salvacorts/TFG-Parasitic-Metaheuristics/issues/13> .
> All non-tech-savvy users could be merged.
>
> Yes, it is the same persona but not the same user story. I think we should
> keep them spearated since implementing one is independent of the other and
> they can work separately.
>
These issues are mainly to create the personas. After you're done, you can
create a series of issues working for every one of them, every one
corresponding to a user story. But for the time being you should keep it
simple with 1 issue == 1 persona.
