### ISSUE TITLE
As a possible contributor, I want to have all functions tested so that my own contributions can be checked before being added.

### ISSUE THREAD

**Issue by JJ** [salvacorts/TFG-Parasitic-Metaheuristics#22]
**User Story**

Tests are essential, and they must be included along with the code, at the same time if possible.

**Acceptance criteria**

If possible, reach 90% coverage in tests.

**Definition of Done**
- [x] Code Builds without error warning
- [x] Code is Unit Tested
- [x] Code is Deployed to system test environment and passed system tests
- [x] Build pushed to a demo server 
- [x] Documentation

**Comment by salvacorts** [comment]
Done
