### ISSUE TITLE
Representación de soluciones

### ISSUE THREAD

**Issue by salvacorts** [salvacorts/TFG-Parasitic-Metaheuristics#3]
Dado que de problema a problema la representación de una solución puede ser muy diferente, ¿cómo podríamos transmitir soluciones independientemente de su representación entre un nodo y el servidor?

**Comment by salvacorts** [comment]
Podemos serializar todo a un JSON.

https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/JSON

**Comment by JJ** [comment]
1. Cierra siempre desde un commit
2. Para ello, tienes que avanzar la documentación. En el TFG tienes que justificar la elección de todas las tecnologías, inclusive serialización. En este caso, JSON es suficientemente popular que otras alternativas (YAML, XML) casi ni se consideran, pero tampoco tiene tipos y se pueden usar capas de abstracción sobre JSON. En todo caso, justificable y en la documentación. 

El hecho de cerrar siempre desde un commit es simplemente para que se quede documentado qué se ha hecho para resolver esa tarea; en este caso está más que justificado.

**Comment by salvacorts** [comment]
Perfecto, gracias. Cerraré la issue cuando se haya documentado e implementado la solución.

**Comment by JJ** [comment]
:+1:

**Comment by JJ** [comment]
These old issues (in Spanish) are living together with the new ones. You can now delete them in GitHub, but I very much prefer that you close them with a documentation commit, even if it's in a ChangeLog file that will not eventually go to the report. As in "Closed old issues, superseded by xxx"

**Comment by salvacorts** [comment]
I've created a changelog where I will write my advances.
