### ISSUE TITLE
As a researcher, I want different systems to communicate between each others with a common solution representation so that all of them can work with it and share it.

### ISSUE THREAD

**Issue by salvacorts** [salvacorts/TFG-Parasitic-Metaheuristics#9]
How to represent a solution to be able to work with it in different languages serializing and deserializing it efficiently.

[Protocol Buffers](https://developers.google.com/protocol-buffers/) seems to be a good option. Another option would be JSON.

**Comment by JJ** [comment]
Protocol buffers are OK if you want to interface a system with different languages. In that case, you should _really_ provide those different clients.

**Comment by salvacorts** [comment]
@JJ Then It would be better to keep this idea in the icebox. If we have time would be nice to create an Android client for example?

**Comment by salvacorts** [comment]
**User Story**
Both browser-based and native nodes need to communicate with each other. By providing a common data structure to represent a solution, nodes will be able to work with the solutions they share with each other. This data structure needs to be flexible by enabling researchers to add all the information they want to this data structure while still providing the basic functionalities that the system needs to work correctly.

**Acceptance criteria**
- Data structure that store meta-information about the candidate solution common to all problems
- Data structure where you can add another problem-specific data structure inside
- Method to print information from the problem-specific data structure

**Definition of Done**
- [x] Code Builds without error warning
- [x] Code is Unit Tested
- [x] Code is Deployed to system test environment and passed system tests
- [ ] Build pushed to a demo server
- [ ] Documentation
